version: "3"
services:
  php82:
    image: skarner2016/php:82
    container_name: php82
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - ../../../workspace:/var/www
      - ./logs/php/81:/var/log/php
    working_dir: /var/www
    restart: always
#    command: [ "/usr/local/bin/php", "/var/www/my-project/la8/artisan", "octane:start", "--watch", "--host=0.0.0.0" ]

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
    working_dir: /var/www
    restart: always

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always