version: '3'

networks:
  monitor:
    driver: bridge

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - 3000:3000
    networks:
      - monitor
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
    restart: always

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter
    hostname: node-exporter
    ports:
      - 9100:9100
    networks:
      - monitor
    restart: always





