version: '3.1'
 
services:
 
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${DOWNLOAD_DIR}:/share
    command: '-p                                              
                -u "skarner;NF@Z&gVKMyg%YZJrusTTKAs$6"
                -s "share;/share/dir1;yes;no;no;skarner;admin;admin;skarner专用"'
