version: "3"
services:
  php:
    build: ./php/74
    ports:
      - 9000:9000
    volumes:
      # - ./config/php:/usr/local/etc/php
      - ./www:/var/www
      - ./logs/php:/var/log/php
    working_dir: /var/www
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - ./config/nginx:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
    working_dir: /var/www
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  mysql57:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql57:/var/lib/mysql
      - ./config/mysql57:/etc/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis:alpine
    # image: redis:latest
    ports:
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ${ZOOKEEPER_DIR}:/data
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ${KAFKA_DIR}:/kafka
    depends_on:
      - zookeeper

  zookeeper2:
    image: wurstmeister/zookeeper
    volumes:
      - ${ZOOKEEPER_DIR}:/data2
    ports:
      - 2182:2182
  kafka2:
    image: wurstmeister/kafka
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9093
      KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    volumes:
      - ${KAFKA_DIR}:/kafka2
    depends_on:
      - zookeeper2