version: '3.1'
 
services:
 
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    restart: always
    ports:
      - 3139:139
      - 3445:445
    volumes:
      - ${DOWNLOAD_DIR}:/share
    command: '-p                                              
                -u "skarner;MninzzHkHNg2P8MxBMLYKKYEg"
                -s "share;/share;yes;no;no;skarner;admin;admin;skarner专用"'


