version: '3.1'
 
services:
 
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./smb:/share
    command: '-p                                              
                -u "skarner;badpass"
                -s "share;/share;yes;no;no;skarner;admin;admin;skarner专用"'


