version: "3"
services:

  v2ray:
    image: v2ray/official:latest
    volumes:
      - /etc/v2ray:/etc/v2ray
    ports:
      - "7000:7000"
      - "7500:7500"
    command: ["v2ray", "-config=/etc/v2ray/config.json"]