version: "3"
services:
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    ports:
      - 3001:3001
    volumes:
      - ./data/uptime:/app/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: always