version: '3'

services:
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:7.17.9
    volumes:
      - ${CONF_SPACE}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ${WORK_SPACE}/skarner2016/test/logs:/docker/www
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.9
    volumes:
      - ${DATA_SPACE}/elasticsearch:/usr/share/elasticsearch/data
      - ${LOG_SPACE}/elasticsearch:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    environment:
      # 开启内存锁定
      - bootstrap.memory_lock=true
      # 修改jvm内存
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # 指定单节点启动
      - discovery.type=single-node
    restart: always

  kibana:
    container_name: kibana
    image: kibana:7.17.9
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      I18N_LOCALE: zh-CN
    restart: always

networks:
  docker_default:
    external:
      name: docker-default