version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK_SET=022
      - WEBUI_PORT=8081 # 将此处修改成你欲使用的 WEB 管理平台端口
    volumes:
#      - /home/qb/config:/config # 绝对路径请修改为自己的config文件夹
      - ${DOWNLOAD_DIR}:/downloads # 绝对路径请修改为自己的downloads文件夹
      - ${QB_DIR}:/qb # 绝对路径请修改为自己的downloads文件夹
    ports:
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 6881:6881
      - 6881:6881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
      - 8081:8081
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    ports:
      - 3139:139
      - 3445:445
    volumes:
      - ${DOWNLOAD_DIR}:/share
    command: '-p                                              
                -u "skarner;NF@Z&gVKMyg%YZJrusTTKAs$6"
                -s "share;/share/dir1;yes;no;no;skarner;admin;admin;skarner专用"'