version: '3'

services:
  php74:
    build:
      context: .
      dockerfile: php74.Dockerfile
    container_name: php74
    ports:
      - 7401:7401
      - 7402:7402
      - 55151:55151
      - 7272:7272
    volumes:
      - ${WORK_SPACE}:/var/www
    stdin_open: true
    tty: true
    working_dir: /var/www
    restart: always
    networks:
      - local_host

  php82:
    build:
      context: .
      dockerfile: php82.Dockerfile
    container_name: php82
    ports:
      - 8201:8201
      - 8202:8202
      - 8203:8203
    volumes:
      - ${WORK_SPACE}:/var/www
    stdin_open: true
    tty: true
    working_dir: /var/www
    restart: always
    networks:
      - local_host

networks:
  local_host:
    driver: bridge