version: '3'

services:
  wordpress:
    image: wordpress:6.4.2-php8.2
    container_name: wordpress
    ports:
      - 9999:80
    volumes:
      - ${WORK_SPACE}:/var/www/html
    stdin_open: true
    tty: true
    working_dir: /var/www/html
    restart: always
    networks:
      - docker_default

networks:
  docker_default:
    driver: bridge