services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ${WORK_SPACE_DATA}/mysql8/data/mysql:/var/lib/mysql
      - ${WORK_SPACE_DATA}/mysql8/data/mysql-files:/var/lib/mysql-files
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS
    networks:
      - local_host

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - local_host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ${WORK_SPACE_DATA}/grafana/grafana-data:/var/lib/grafana
      - ${WORK_SPACE_DATA}/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - local_host

networks:
  local_host:
    driver: bridge