version: '3'

services:
  go19:
    image: golang:1.19.7-alpine3.17
    container_name: go19
    ports:
      - 1901:1901
    volumes:
      - ${WORK_SPACE}:/var/www
    stdin_open: true
    tty: true
    working_dir: /var/www
    restart: always
    networks:
      - docker_default

networks:
  docker_default:
    driver: bridge